services:
  # Main Backend Application
  api:
    image: node:20-alpine
    container_name: openedu-api
    restart: unless-stopped
    working_dir: /app
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser
      - PUPPETEER_ARGS=--no-sandbox --disable-setuid-sandbox --disable-dev-shm-usage --disable-gpu --single-process
      # MinIO endpoints for internal/external access
      - MINIO_ENDPOINT_INTERNAL=minio
      - MINIO_ENDPOINT_EXTERNAL=localhost:9000
      - MINIO_PORT=9000
      - MINIO_USE_SSL=false
      - REDIS_URL=redis://:openedu_redis_dev@redis:6379
    env_file:
      - .env
    ports:
      - "8081:8081"
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - .:/app
    networks:
      - openedu-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    command: >
      sh -c "
        apk add --no-cache bash python3 make g++ cairo-dev jpeg-dev pango-dev musl-dev giflib-dev pixman-dev pangomm-dev libjpeg-turbo-dev freetype-dev ffmpeg curl chromium &&
        npm install &&
        npm i -g @marp-team/marp-cli &&
        npm run build &&
        npm prune --production &&
        echo 'FFmpeg version:' && ffmpeg -version | head -1 &&
        echo 'Marp CLI version:' && marp --version &&
        npm run start:prod
      "

  # PostgreSQL Database with pgvector extension
  db:
    image: ankane/pgvector:latest
    container_name: openedu-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: openedu
      POSTGRES_PASSWORD: Qt5ff3c6RDkGBTpuALBap1juR7uXjJlSG0cmSn54FZI=
      POSTGRES_DB: openedu_db
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U openedu -d openedu_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - openedu-network


  # MinIO Object Storage
  minio:
    image: minio/minio:latest
    container_name: openedu-minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: AKIAIOSFODNN7EXAMPLE
      MINIO_ROOT_PASSWORD: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      # Optional: Set external hostname for presigned URLs
      # MINIO_BROWSER_REDIRECT_URL: "http://your.external.host:9000"
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - openedu-network

  # MinIO Setup - Creates required buckets and sets policies
  minio-setup:
    image: minio/mc:latest
    container_name: openedu-minio-setup
    depends_on:
      minio:
        condition: service_healthy
    # Use a shell entrypoint to run multiple commands
    entrypoint: ["/bin/sh", "-c"]
    command: |
      # Wait until alias set works
      until mc alias set local http://minio:9000 AKIAIOSFODNN7EXAMPLE wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY; do
        echo "Waiting for MinIO to become ready..."
        sleep 2
      done &&
      # Create required buckets (if not exist)
      mc mb local/courses || true
      mc mb local/certificates || true
      mc mb local/documents || true
      mc mb local/profiles || true
      mc mb local/audio || true
      mc mb local/slides || true &&
      # Set ALL buckets to private (no anonymous access)
      mc anonymous set private local/courses || true &&
      mc anonymous set private local/certificates || true &&
      mc anonymous set private local/documents || true &&
      mc anonymous set private local/profiles || true &&
      mc anonymous set private local/audio || true &&
      mc anonymous set private local/slides || true &&
      echo "Buckets + anonymous policies configured" &&
      exit 0
    networks:
      - openedu-network

  redis:
    image: redis:7-alpine
    container_name: openedu-redis
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "openedu_redis_dev"]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - openedu-network

  # Pgweb - Web UI for PostgreSQL
  pgweb:
    image: sosedoff/pgweb:latest
    container_name: openedu-pgweb
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://openedu:Qt5ff3c6RDkGBTpuALBap1juR7uXjJlSG0cmSn54FZI=@db:5432/openedu_db?sslmode=disable
    ports:
      - "8082:8081"
    networks:
      - openedu-network

volumes:
  pgdata:
    driver: local
  minio_data:
    driver: local
  redis-data:
    driver: local

networks:
  openedu-network:
    name: backend_openedu-network
    driver: bridge